### ISSUE TITLE
Generate a j8a config file by reading ingress.yml

### ISSUE THREAD

**Issue by simonmittag** [simonmittag/ingress-j8a#9]
# Why?
We need to be able to (re) generate the j8a config from ingress.yml and it's changes.

# What?
- Read ingress.yml and pluck whitelisted values
- merge with template that includes sensible defaults for fine grained j8a config
- (optional) allow overriding of optional values with meta tags in ingress.ym. (check if this is legal)

# How?
- Generate as json, then convert to yml. Take hints from j8a code.
- needs to read links to TLS certs from ingress.yml, follow links and then import them into j8a.config
- (optional) validate config against external j8a cli

**Comment by simonmittag** [comment]
Minimal ingress example: 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```

**Comment by simonmittag** [comment]
TLS ingress example

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo.mlopshub.com
    secretName: hello-app-tls
  rules:
  - host: "demo.mlopshub.com"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: hello-service
              port:
                number: 80
```
